### ISSUE TITLE
Mask definitions are not supported

### ISSUE THREAD

**Issue by steveharoz** [dotnetprojects/SVGImage#1]
I'm not sure if it's feasible to fix. But it's worth stating that this feature won't work.

**Comment by jogibear9988** [comment]
as it is possible in xaml:
https://docs.microsoft.com/de-de/dotnet/framework/wpf/graphics-multimedia/opacity-masks-overview
we should be able to support it in the control

**Comment by jogibear9988** [comment]
fixed
