### ISSUE TITLE
[Wish] Expose the SVG object model

### ISSUE THREAD

**Issue by raffaeler** [dotnetprojects/SVGImage#10]
There are cases (see the example I posted here https://github.com/dotnetprojects/SVGImage/issues/9 ) where the application need to know more info from the object drawn inside the SVG.
For example you may need how many paths are described in the file, and also where they are so that you can draw an adorner over a specific path.
In other cases you may need to make small changes like changing the foreground, background or stroke of a specific object (line, rectangle, path, etc.)

I have no clue what is the effort, but I was wondering if you could expose the SVG object model, right after having parsed it, so that the application can avoid to re-parse it to get this info.
Thank you

**Comment by jogibear9988** [comment]
With my last commit smth like this is possible:

      ((SolidColorPaintServer) ((RectangleShape) a.SVG.Elements[0]).Fill.Color).Color = Colors.Yellow;
      a.ReRenderSvg();

where a is a SvgImage (yours 2.svg)

**Comment by raffaeler** [comment]
Thank you, I will try with the paths coordinates

**Comment by raffaeler** [comment]
@jogibear9988 I tried to access the SVG property during the OnLoad event of the control, but it is null.
I need to access the SVG object model as soon as the file is loaded in memory. What is the event I should hook to access the SVG property?

Thanks
