### ISSUE TITLE
Control crashes loading a SVG file

### ISSUE THREAD

**Issue by Cairn23** [dotnetprojects/SVGImage#14]
I was loading a number of SVG files, testing some svg files. In some instances the application crashed, so I traced the problem to ShapeUil ParseTransformInternal. The problem was that the string had a leading space which resulted in returning a null to ParseTrasnform.
The solution is to call trim on value before any other calls are made within the function

**Comment by jogibear9988** [comment]
could you create a pull req?

**Comment by jogibear9988** [comment]
no answer

**Comment by Cairn23** [comment]
Given I provided the info you could implement it within the code

**Comment by jogibear9988** [comment]
I‘ve no time to do it, I‘ve no image wich fails.

**Comment by paulushub** [comment]
Was able to duplicate the exception with other files and the effect of the space with the following from the Mozilla website
```svg
<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
  <!-- No translation -->
  <rect x="5" y="5" width="40" height="40" fill="green" />
 
  <!-- Horizontal translation -->
  <rect x="5" y="5" width="40" height="40" fill="blue" transform=" translate(50) " />
 
  <!-- Vertical translation -->
  <rect x="5" y="5" width="40" height="40" fill="red" transform="translate(0 50)" />
 
  <!-- Both horizontal and vertical translation -->
  <rect x="5" y="5" width="40" height="40" fill="yellow" transform="translate(50,50)" />
</svg>
```
