### ISSUE TITLE
Suggestions - Evolving

### ISSUE THREAD

**Issue by paulushub** [dotnetprojects/SVGImage#16]
Currently, developing and maintaining SharpVectors, but could contribute to this library too.
Have you made releases? Nuget package? Is there any problem with breaking interfaces to current users?

Please consider the following:
1. A better namespace and .NET compliant naming. 
    - Currently, namepace=SVGImage.SVG and assembly=DotNetProjects.SVGImage
    - And the control is name is SVGImage.
    - Also, you have DotNetProjects.SVGImage.SVG.FileLoaders
    - Something like SvgXaml, SvgWpf or SvgImages (then you have SvgXaml.IO, SvgXaml.Shapes, SvgXaml.Filters or Effects to include Clip and Mask, SvgXaml.Animations, SvgXaml.Css) etc.
    - And the control can be SvgImage (similar to [SvgImageSource](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imaging.svgimagesource?view=winrt-19041)), a lightweight viewer for UWP applications.
    - Then the SVG class to SvgDocument or SvgModel etc
2. Add an improved CSS library. Some lightweight parsers on Codeproject (maybe updated versions on Github)
    - [Simple CSS Parser](https://www.codeproject.com/Articles/20450/Simple-CSS-Parser)
    - [A Simple CSS Parser](https://www.codeproject.com/Articles/335850/CSSParser)

Hopefully, the current users will contribute to this thread to evolve this library as a lightweight viewer of Svg files in WPF.

**Comment by jogibear9988** [comment]
I've added you.
Currently Package is released, nuget is automatically build and published when a pull req is merged.
Breakingen changes could be introduced, but then we should increase major. (in appveyor.yml)

**Comment by jogibear9988** [comment]
I think I searched for a css parser when I worked on css code some time ago (https://github.com/dotnetprojects/SVGImage/commit/b4179061ba0a1e2b825103629474eac4656c3a58) but I then did not use one, don't know why any more.

Also AngleSharp has a css parser.

**Comment by paulushub** [comment]
It seems I do not have access. I have created a pull request, please review it and merge.

**Comment by jogibear9988** [comment]
i‘ve added you

**Comment by jogibear9988** [comment]
anglesharp has also a css parser

**Comment by paulushub** [comment]
> anglesharp has also a css parser

True, but keeping this library compact and without dependency on other packages will make it more attractive to those looking for simple SVG image features in application, similar to `SvgImageSource` for UWP, which does not support CSS.

`AngleSharp.Css` depends on `AngleSharp`, which requires .NET 4.6 or later etc

**Comment by jogibear9988** [comment]
yes, don‘t what functionalty of a css parser we need.
maybe we could make it switchable. 
some simple included, or a full blown from a external lib

in anglesharp you could also use an other css parser (but i think noone will do 😊)

**Comment by jogibear9988** [comment]
https://github.com/AngleSharp/AngleSharp/issues/898

**Comment by paulushub** [comment]
@jogibear9988 @williamgarner The W3C Test Suite application is now in repository together with the simple test application to debug issues.
You can get your hands dirty, especially with the Test Suite, marking test states: Failure, Partial or Success.
The default test is SVG 1.1 Full, but you can change to SVG 1.2 Tiny in the Settings Tab.
I have completed all the works I promised!!!
