### ISSUE TITLE
Cannot display SVG-file when nesting in containers

### ISSUE THREAD

**Issue by McTopaz** [dotnetprojects/SVGImage#19]
I have a WPF-application where I want to display SVG-files.

In my application I have several `DockPanels` and `StackPanels` nested to get my layout as I want.
Deep down in the nested I have a `SVGImage` control.
But when the `SVGImage` control is nested in a container and the container contains some other controls, the `SVGImage` control disapears. 

I have manage to reproduce the problem with three examples:
### Working
<Window x:Class="TestWpf.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:TestWpf"
        xmlns:svg="clr-namespace:SVGImage.SVG;assembly=DotNetProjects.SVGImage"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">

    <Border BorderBrush="Black" BorderThickness="0" CornerRadius="{Binding CornerRadius}">
        <DockPanel LastChildFill="True">
            <svg:SVGImage Source="/TestWpf;Component/Images/alert_triangle.svg" DockPanel.Dock="Left" />
        </DockPanel>
    </Border>
</Window>

### Not wokring
<Window x:Class="TestWpf.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:TestWpf"
        xmlns:svg="clr-namespace:SVGImage.SVG;assembly=DotNetProjects.SVGImage"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">

    <Border BorderBrush="Black" BorderThickness="0" CornerRadius="{Binding CornerRadius}">
        <DockPanel LastChildFill="True">
            <svg:SVGImage Source="/TestWpf;Component/Images/alert_triangle.svg" DockPanel.Dock="Left" />
            <StackPanel Orientation="Vertical" DockPanel.Dock="Right">
                <TextBlock Text="Foo" FontSize="20" />
                <TextBlock Text="Bar" FontSize="16" />
            </StackPanel>
        </DockPanel>
    </Border>
</Window>

### Not wokring
<Window x:Class="TestWpf.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:TestWpf"
        xmlns:svg="clr-namespace:SVGImage.SVG;assembly=DotNetProjects.SVGImage"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">

    <Border BorderBrush="Black" BorderThickness="0" CornerRadius="{Binding CornerRadius}">
        <DockPanel LastChildFill="True">
            <svg:SVGImage Source="/TestWpf;Component/Images/alert_triangle.svg" DockPanel.Dock="Left" />
            <TextBlock Text="ASDF" DockPanel.Dock="Right" />
        </DockPanel>
    </Border>
</Window>

What could be the problem?

**Comment by jogibear9988** [comment]
It's cause of how the control works.

If you add a height&width it works.
The Control does not request a minimum size

**Comment by jogibear9988** [comment]
Try adding  SizeType="SizeToContent"

**Comment by jogibear9988** [comment]
Please close issue if this works

**Comment by McTopaz** [comment]
That got it working!
Thank you!
