### ISSUE TITLE
License of this repository is not under GNU

### ISSUE THREAD

**Issue by amigup** [dotnetprojects/SVGImage#2]
Hello Jochen,

Thanks for this repository. However, this repository is licensed under CPOL which is incompatible with the GNU General Public License and some other free software licenses, and inconsistent with the Open Source Definition. Can you please put this repository under GNU license so that it can be used according to Open Source definition?

Thanks,
Amit

**Comment by jogibear9988** [comment]
as I‘m not the original author (it‘s only a fork), I can not do!

**Comment by jogibear9988** [comment]
If you ask the author, and he allows, I will seitch. But maybe you could ask if we could use MIT Licence

**Comment by amigup** [comment]
Thanks jogibear, I'm unable to find the email address of the author (jkristia). Do you have his contact email address?

**Comment by jogibear9988** [comment]
nope

**Comment by amigup** [comment]
Hello @jogibear9988, It seems that @jkrisitia exists on github (userId - jkristia). However, I can not tag him as he is not a contributor of this repository. Need a favor from you --- can you please add him to this repository so that he can be tagged and notified.

**Comment by jogibear9988** [comment]
I‘ve invited him

**Comment by jogibear9988** [comment]
i got an answer!
licence change is possible, i will do it

**Comment by jogibear9988** [comment]
Licence is now MIT

**Comment by amigup** [comment]
Thanks.
