### ISSUE TITLE
It does not work in my wpf Project

### ISSUE THREAD

**Issue by kouroshkashi** [dotnetprojects/SVGImage#36]
I want use SVG file as a button image but it does not show.

**Comment by paulushub** [comment]
The test samples use button images in toolbars are other places:
https://github.com/dotnetprojects/SVGImage/tree/master/Tests/SvgTestBox
https://github.com/dotnetprojects/SVGImage/tree/master/Tests/SvgTestSuites

**Comment by jogibear9988** [comment]
@kouroshkashi does it work now? can i close?

**Comment by Gedd18** [comment]
Sometimes the SvgImage need a call to SetImage function to be well displayed
Hope this help

**Comment by paulushub** [comment]
@Gedd18 Please can you explain the situation further, maybe with sample code for testing?

**Comment by Gedd18** [comment]
> @Gedd18 Please can you explain the situation further, maybe with sample code for testing?

When you set the Source property of a SVGImage for example, no update until you call SetImage.

```
public string Source
        {
            get => img.Source;
            set
            {
                img.Source = value;
                Uri _uri = new Uri("pack://application:,,," + img.Source);
                StreamResourceInfo sri = Application.GetResourceStream(_uri);

                using (Stream s = sri.Stream)
                {
                    img.SetImage(s);
                }
            }
        }
```

**Comment by paulushub** [comment]
> When you set the Source property of a SVGImage for example, no update until you call SetImage.

@Gedd18 Thanks for the update. What is **img** is your code sample? Is `Source` a property in your own application/control?

**Comment by Gedd18** [comment]
Sorry it's not very explicit.
img is an instance of a SVGImage object.
Its a part from my project SWUI on Github : [SVGButton](https://github.com/Gedd18/swui/blob/main/src/swui/SVGButton.xaml.cs)

**Comment by paulushub** [comment]
OK! I get you. There is a problem with the way URI is resolved by the SVGImage. So, it is not the `SetImage` is required but you are resolving the pack URI in your codes.
I do not know if there is a way to fix this without breaking existing codes. I could add a new property `UriSource` to properly resolve the URI so that you can simply write
```
UriSource="/svg/happy.svg"

instead of the current
Source="/SWUI.Sample;component/svg/happy.svg"
```

**Comment by Gedd18** [comment]
Thanks, i try this as soon as possible and i give you feedback.

**Comment by jogibear9988** [comment]
I close this. If it does not work, feel free to reopen.
