### ISSUE TITLE
Parametrize foreground color

### ISSUE THREAD

**Issue by sderrico** [dotnetprojects/SVGImage#4]
Hello,

We use multiple svg files that constitute our application buttons. The brush is solid black for all svg files. Is it possible to render them with another colour depending of an application setting?

An example would be:

`<svg1:SVGImage Source="/Example;component/Images/ButtonCenter.svg" Foreground="{DynamicResource PrimaryTextColorBrush}" />`

Thank you,
Sebastien

**Comment by jogibear9988** [comment]
Try OverrideColor="Black" in newest Version

**Comment by sderrico** [comment]
It works, thank you!
