### ISSUE TITLE
Svg will not display if SvgImage created dynamically

### ISSUE THREAD

**Issue by cuiliang** [dotnetprojects/SVGImage#40]
When control  was created as a child elememnt of other control like this:
```
var img = new SVGImage.SVG.SVGImage()
                                    {
                                       ImageSource =  svgDrawing,
                                       VerticalContentAlignment = VerticalAlignment.Center,
                                       HorizontalContentAlignment = HorizontalAlignment.Center
                                    };
                                    Content = img;
```
The image will not show.
Maybe because when it was first measred, MeasureOverride returned Size.Zero.

can be fixed:
```
 protected override Size MeasureOverride(Size constraint)
        {
            //Size result = base.MeasureOverride(constraint);

            Size result = constraint;

            if (this.SizeType == eSizeType.SizeToContent)
            {
                if (this.m_drawing != null && !this.m_drawing.Bounds.Size.IsEmpty)
                    result = this.m_drawing.Bounds.Size;
            }

            if (constraint.Width > 0 && constraint.Width < result.Width)
                result.Width = constraint.Width;
            if (constraint.Height > 0 && constraint.Height < result.Height)
                result.Height = constraint.Height;

            return result;
        }
```
But I am not sure if this is the right way.

**Comment by paulushub** [comment]
@cuiliang Can you post a working sample code for test?

**Comment by cuiliang** [comment]
[demo.zip](https://github.com/dotnetprojects/SVGImage/files/6398312/demo.zip)

Hello~
unzip demo.zip, open SVGImage.sln，Run `"WpfApp1"` project. This is modified version of SVGImage.


![image](https://user-images.githubusercontent.com/1972649/116547374-5f23d500-a925-11eb-81af-b64617828cc7.png)


If change SVGImage.MeasureOverride to origin code, the svg image will not show.

![image](https://user-images.githubusercontent.com/1972649/116547592-ad38d880-a925-11eb-8636-e7f16dc7bf2a.png)

![image](https://user-images.githubusercontent.com/1972649/116547630-b9bd3100-a925-11eb-96e3-8daa429dab42.png)

**Comment by paulushub** [comment]
@cuiliang Thanks for the cooperation. I really do not know if this is an issue.
You are putting the `SVGImage` in a content control whose size is not set, and
default stretching or sizing mode of the `SVGImage` is `ContentToSizeNoStretch`,
so with no content size the `result` beomes zero size.

I think in this situation, you simply have to set the sizing to `SizeToContent`, so that
the content control is sized to the rendered drawing size. This actually works
```cs
var imgCtrl = new SVGImage.SVG.SVGImage()
{
    ImageSource = svgDrawing,
    SizeType = SVGImage.SVG.SVGImage.eSizeType.SizeToContent,
    VerticalContentAlignment = VerticalAlignment.Center,
    HorizontalContentAlignment = HorizontalAlignment.Center
};
```
But to prevent returning zero size when there is a drawing, which can be confusing,
I will add a check after the size computations as below:
```cs
if (result.IsEmpty)
{
    if (this.m_drawing != null && !this.m_drawing.Bounds.Size.IsEmpty)
        result = this.m_drawing.Bounds.Size;
}
```

**Comment by cuiliang** [comment]
Ok, Thank you~
