### ISSUE TITLE
Assembly strong name is missing

### ISSUE THREAD

**Issue by knappema** [dotnetprojects/SVGImage#41]

**Comment by jogibear9988** [comment]
https://github.com/dotnet/runtime/blob/main/docs/project/strong-name-signing.md

**Comment by paulushub** [comment]
All assemblies in the SharpVectors have strong name to prevent conflicts. Anyone who really need assemblies without strong name may be doing drop-in replacement, he/she should be building all.

**Comment by knappema** [comment]
@jogibear9988 What exactly was the reason why the issue was closed? According to the link https://github.com/dotnet/runtime/blob/main/docs/project/strong-name-signing.md, a strong name is recommended for libraries ("... it is recommended that publicly published .NET libraries are strong-named"). And there are no disadvantages resulting from it.
