### ISSUE TITLE
CustomBrushes Binding Problem

### ISSUE THREAD

**Issue by Doeharrrck** [dotnetprojects/SVGImage#42]
I have tried to bind the `CustomBrush` property `SVGImage` to a `ToggleButton`'s foreground. The issue is described also here: [https://stackoverflow.com/questions/66281489/ivalueconverter-not-called-on-relativesource-ancestor](https://stackoverflow.com/questions/66281489/ivalueconverter-not-called-on-relativesource-ancestor).

I also created this demo project: [https://github.com/Doeharrrck/NavButton](https://github.com/Doeharrrck/NavButton).

The desired behavior is that the icon should change it's color the same way as the text below on events like hover, press, check changed however it remains black.

The problem seems to be in the `OnInitialized` method of the `SVGImage` class. It works if I comment the last line in it so I have already a working solution.

However, it is not clear to me which feature I might have broken by commenting that line. I observed no negative consequences so far.

**Comment by jogibear9988** [comment]
it was introduced here https://github.com/dotnetprojects/SVGImage/commit/a0c2612aef1ab51a23f4fc7a0acb758d4f8133e6 by @williamgarner 
maybe he could help

**Comment by williamgarner** [comment]
Hello @Doeharrrck,

Custom Brushes need to be bound using `Mode=TwoWay`. This allows the manipulation of very complex SVG images. I pulled your code and made that change. He is the result:

![navButton](https://user-images.githubusercontent.com/43454784/108917443-95bb3780-75e4-11eb-911e-ab2c54392def.gif)

Does this solve your issue?

**Comment by Doeharrrck** [comment]
Hi, this is working also in my real project. Thank you very much!
