### ISSUE TITLE
Environment.CurrentDirectory prevents msix packaging

### ISSUE THREAD

**Issue by DuncanStone** [dotnetprojects/SVGImage#43]
Projects using this library can't be packaged to msix installers because Environment.CurrentDirectory resolves to a system folder e.g. C:\Windows\SysWOW64 (for x64 builds).

Changing the file path resolution to use Path.GetDirectoryName(System.Reflection.Assembly.GetEntryAssembly().Location) should solve this issue

**Comment by paulushub** [comment]
@DuncanStone A fix is committed, please verify this issue.

**Comment by DuncanStone** [comment]
What do I have to do to ensure that I have the fix locally?

**Comment by paulushub** [comment]
Sorry, it is now committed. How are you packaging the msix? Are you using the Nuget package or the DLL?
You can checkout and build the source.

**Comment by jogibear9988** [comment]
@paulushub nuget should be published automatically when you merge smth. to master

**Comment by paulushub** [comment]
@jogibear9988 I made a mistake of asking for verification before the merge. I normally do not publish code until verified by the user. Maybe you have to create a developer branch to handle development.

**Comment by jogibear9988** [comment]
i will not do this. no time, i'm too much into other projects.
If you'd like to, feel free to do so :-)
I work on too many Open Source Projects

**Comment by paulushub** [comment]
@jogibear9988 Also busy with many stuff. But these issues were posted long ago, it might give an impression of abandon project.

**Comment by DuncanStone** [comment]
The fixes look good to me. I don't really have time to fully test it. I am ok with this being closed.

**Comment by paulushub** [comment]
@DuncanStone Thank you. If you still have any issue, reopen it.
