### ISSUE TITLE
Images do not reload on OverrideColor change

### ISSUE THREAD

**Issue by Fi0x** [dotnetprojects/SVGImage#48]
When I change the `OverrideColor` property, the image does not get re-loaded with the new value.
I have to use a workaround that uses `SetImage`.

But I don't think that this is intentional?

**Comment by jogibear9988** [comment]
does it work when you call https://github.com/dotnetprojects/SVGImage/blob/80c89fbf6a3aa2551018cae156aaf761bc97696c/Source/SVGImage/SVG/SVGImage.cs#L221

then i think we need a ChangeNotification in this dependecy property:

https://github.com/dotnetprojects/SVGImage/blob/80c89fbf6a3aa2551018cae156aaf761bc97696c/Source/SVGImage/SVG/SVGImage.cs#L92

but I've no time to work on this at the moment. Maybe you could and create a pull req?

**Comment by DrCopyPaste** [comment]
I think there was only one OverrideColorPropertyChanged missing for the OverrideColor property.
I had a similar issue and forked this repo with only this one change:

https://github.com/DrCopyPaste/SVGImage/commit/a7907457e9059e6e7f0ebcf08a497e15fdc56109

(But did not make a PR yet, coz I wanted to test it and the branch name still reflects my first stupid attempt to fix it somewhere else :D)

**Comment by DrCopyPaste** [comment]
Had the same issue, was able to reproduce this in a simple sample on the example app (double click the rect-image to randomly change color)

https://github.com/dotnetprojects/SVGImage/pull/49
