### ISSUE TITLE
Suggestion to make appVeyor build

### ISSUE THREAD

**Issue by sderrico** [dotnetprojects/SVGImage#5]
Hello,

I tried to create a pull request but I do not have the permission. I suspect the automatic appVeyor build does not support C#7 feature. 

Do you think those replacement lines will fix the automatic build then it will generate a new NuGet version?

Thank you!

### 1. replace line 170 from SVGRender.cs
```
if (shape is AnimateTransform animateTransform)
```
**by**
```
if (shape is AnimateTransform)
{
    var animateTransform = shape as AnimateTransform;
```

### 2. replace line 187 from SVGRender.cs
```
else if (shape is Animate animate)
```
**by**
```
else if (shape is Animate)
{
    var animate = shape as Animate;
```

**Comment by jogibear9988** [comment]
sorry, I've not seen that the build didn't work

**Comment by jogibear9988** [comment]
it's fixed by switching appveyor to vs2017

**Comment by jogibear9988** [comment]
don't know why you cannot create a pull req
