### ISSUE TITLE
"Cannot locate resource"

### ISSUE THREAD

**Issue by martin-braun** [dotnetprojects/SVGImage#56]
<img width="482" alt="Screen Shot 2021-11-01 at 01 53 12" src="https://user-images.githubusercontent.com/24259245/139607750-f95eadca-5fa0-4954-a16d-a5877872ea05.png">

I've set the build action to Resource, but it's still not working.

**Comment by paulushub** [comment]
@martin-braun I do not think there is a design-time support. I have not tested it, it will hopefully work in runtime. If not, try the `SvgIcon` (see the samples for uses).

**Comment by martin-braun** [comment]
@paulushub It didn't compile for the same reason I think. SharpVector on the other hand works (also at design time, just not reliably), so I think here is room for improvement. 

Due to time-pressure I had to move on and use SharpVector now. If you cannot reproduce the issue, I have no problem when you close this issue, I just wanted to report this issue on my end whatsoever. Maybe someone else can confirm my observation, maybe it was just me.

**Comment by paulushub** [comment]
@martin-braun That is part of the original code and you cannot modify it without breaking existing codes using it. Also, the build is set for automatic nuget updates so versioning is not controlled.

I have added `UriSource` as an alternative so I saw the limitation (just remembered) - so try using that property.

**Comment by jogibear9988** [comment]
The Control also worked at design time (some time ago). So some change broke it, but for me this was not critical, so I never investegated into it.
We completly switch to an html UI so I nearly don't use this library

**Comment by paulushub** [comment]
> The Control also worked at design time (some time ago). 

Probably referring to Visual Studio dependent `SVGImage.Design` project. You might need to update it to work with various versions of the Visual Studio and make a nuget package available.
