### ISSUE TITLE
stroke="rgb(255, 0,0)" results to green while stroke="red" works fine

### ISSUE THREAD

**Issue by joergk680** [dotnetprojects/SVGImage#60]
Hi,

is there a way to configure color mapping, so I get valid results when color values are given as RGB values?
Example:
stroke="rgb(255, 0,0)" is shown as green while stroke="red" works fine

Test files with RGB and named colors are attached.

![image](https://user-images.githubusercontent.com/105711044/168776221-99bdd5bd-bad4-40d9-b813-9824a8c1d38e.png)

Greetings,
Jörg

![0_rgb](https://user-images.githubusercontent.com/105711044/168775889-c627a790-a1c3-43ed-b6ab-a6db11003b89.svg)
![0_named](https://user-images.githubusercontent.com/105711044/168775891-13d8b8fd-5f32-4240-b7e2-07e941ba234f.svg)

**Comment by paulushub** [comment]
For some reason (probably poor design choices), SVGImage first converts all colors to hex-format. The conversion of the RGB to HEX is wrong (rgb(255, 0,0) gives #ff00).
