### ISSUE TITLE
SVGimage ignore transparent regions which are neccesary.  

### ISSUE THREAD

**Issue by TruePluto** [dotnetprojects/SVGImage#67]
I have a SVG icon which contains a triangle at the right down corner and left other regions transparent.
when I show the SVG icon via SVGImage

```
<svg:SVGImage
     x:Name="ExpandPath"
     UriSource="/SegmentOperation;component/Svgs/Arrow_Right.svg" />
```
or SVGIcon
```
<Image x:Name="ExpandPath" Stretch="Uniform" 
     Source="{Binding Converter={svg:SvgIconConverter}, 
     ConverterParameter=/SegmentOperation;component/Svgs/Arrow_Down.svg, Mode=OneWay}"/>
```
The result is two triangles stretch to the full contents. the deliberated transparent regions are missing. but I need the two triangles stay at right down corner correctly. What do I missing?
thanks for your attention.

**Comment by jogibear9988** [comment]
With both of this controls it only possible what WPF can do with xaml images. I don't know if your issue is solveable. Maybe if you upload your SVG here someone can look. But I don't know if I find the time. I mostly don't use WPF at the moment.
If you create a Pull, I would merge it.

**Comment by jogibear9988** [comment]
i've added a fix for transparent fill brushes, maybe this helps you also

**Comment by ReIaxo** [comment]
Hi, I have a similar problem. I want to use the [Google Material Icons](https://fonts.google.com/icons?icon.style=Outlined&icon.set=Material+Symbols&selected=Material+Symbols+Outlined:home:FILL@0;wght@300;GRAD@0;opsz@48). They have a padding to each side. This Padding is ignored by SVGImage control.
Is it possible to respect the padding?

Which fix do you mean? How should I configure the SVGImage control?
![MicrosoftTeams-image](https://github.com/dotnetprojects/SVGImage/assets/44195536/9ee6d77f-65e9-423c-a714-fa58b2a794da)

**Comment by jogibear9988** [comment]
I don‘t think this is a similar problem, so a new issue would be better.
But as I said, i do not work much mit WPF at the moment, so if you create a pull req, I could merge, otherwise you will be stuck with the issue
