### ISSUE TITLE
Opacity is not Work.

### ISSUE THREAD

**Issue by oyg049** [dotnetprojects/SVGImage#68]
I used SvgIconConberter, But Svg opacity(also fill-opacity) is not work.

Use Code
`<Image Source="{Binding Contents.CurrentContents.Path, Converter={svg:SvgIconConverter}}" Stretch="Uniform"/>`

Svg File Code

`<svg version="1.1" id="레이어_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px"
	 y="0px" viewBox="0 0 40 40" style="enable-background:new 0 0 40 40;" xml:space="preserve">
<path
	style="fill:#2ac8e8;"
	d="M0.1996008,21 v 9.474734 c 0,4.737368 3.9600799,8.527262 8.9101796,8.527262 H 30.89022 c 4.9501,0 8.910179,-3.789894 8.910179,-8.527262 V 21" />
<path
	style="fill:rgb(42,200,232);fill-opacity:0.8;"
	d="M1,12 h 38 v 9 H 1 Z" />
<path
	style="fill:rgb(42,200,232);fill-opacity:0.5;"
	d="M1,7 h 38 v 5 H 1 Z" />
<path 
	style="fill:rgb(42,200,232);fill-opacity:0.2;"
	d="M7,1h26c3.3,0,6,2.7,6,6l0,0l0,0H1l0,0l0,0C1,3.7,3.7,1,7,1z" />
<path
	style="fill:none;stroke:#464D62;"
	d="M9,0.5h22c4.7,0,8.5,3.8,8.5,8.5v22c0,4.7-3.8,8.5-8.5,8.5H9c-4.7,0-8.5-3.8-8.5-8.5V9C0.5,4.3,4.3,0.5,9,0.5z" />
</svg>`

![worng](https://user-images.githubusercontent.com/91577177/231367438-30e07f48-0149-4c83-b90c-9cd0f78fe89c.PNG)

**Comment by jogibear9988** [comment]
should be fixed
