### ISSUE TITLE
Not rendering inside of a button

### ISSUE THREAD

**Issue by sderrico** [dotnetprojects/SVGImage#7]
Hello,

Do you know why the image does not reder inside of a button?

```
        <Button>
            <svg1:SVGImage Source="/Example;component/Images/PhotoEditor/ButtonDeleteImage.svg" OverrideColor="blue"/>
        </Button>

```

Thank you!
Sebastien

**Comment by jogibear9988** [comment]
maybe missing size?

**Comment by sderrico** [comment]
You are right, the image is visible as soon there is a size.

Do you know how to mimic the Image behavior that is taking his container size?

Thank you

**Comment by jogibear9988** [comment]
There is 

  SizeType="SizeToContent"

**Comment by sderrico** [comment]
Thank you!
