### ISSUE TITLE
Padding from SVG is ignored by SVGImage control

### ISSUE THREAD

**Issue by ReIaxo** [dotnetprojects/SVGImage#72]
Hi, I want to use the [Google Material Icons](https://fonts.google.com/icons?icon.style=Outlined&icon.set=Material+Symbols&selected=Material+Symbols+Outlined:home:FILL@0;wght@300;GRAD@0;opsz@48). They have a padding to each side. This Padding is ignored by SVGImage control.
Is it possible to respect the padding?
Or can someone point me in the right direction to fix it by myself?

![MicrosoftTeams-image](https://github.com/dotnetprojects/SVGImage/assets/44195536/9ee6d77f-65e9-423c-a714-fa58b2a794da)

EDIT:
Here is the svg of the Home image:
```svg
<svg xmlns="http://www.w3.org/2000/svg" height="48" viewBox="0 -960 960 960" width="48">
    <path d="M225.385-185.385h155.77v-245h197.69v245h155.77v-381.922L480-759.23 225.385-567.436v382.051Zm-45.384 45.384v-449.998L480-815.767l299.999 225.768v449.998H533.462v-245H426.538v245H180.001ZM480-472.615Z"/>
</svg>
```

**Comment by paulushub** [comment]
@ReIaxo Sorry, I do not understand your request well, Of the two images you displayed, which one do you want?

**Comment by ReIaxo** [comment]
I want the second one, repecting the padding (is it called padding in svg context?)

**Comment by paulushub** [comment]
> I want the second one, repecting the padding (is it called padding in svg context?)

Thanks, it is fixed with the recent update - **ViewBoxToSizeNoStretch**.
![image](https://github.com/dotnetprojects/SVGImage/assets/809351/bcfbc823-76c3-42ea-95c2-f55d8e438efc)

NOTE: I was not expecting **None** to display empty drawing - looking into it.

**Comment by apweili** [comment]
> > I want the second one, repecting the padding (is it called padding in svg context?)
> 
> Thanks, it is fixed with the recent update - **ViewBoxToSizeNoStretch**. ![image](https://user-images.githubusercontent.com/809351/278026488-bcfbc823-76c3-42ea-95c2-f55d8e438efc.png)
> 
> NOTE: I was not expecting **None** to display empty drawing - looking into it.

Hi, our project uses this controller by Nuget, could you update the package on Nuget including this fixup?

**Comment by paulushub** [comment]
> Hi, our project uses this controller by Nuget, could you update the package on Nuget including this fixup?

Working on it. The last commit failed tests in one use case (by a sample application), and just fixed the above **None** case so requires more testing.

**Comment by apweili** [comment]
> > Hi, our project uses this controller by Nuget, could you update the package on Nuget including this fixup?
> 
> Working on it. The last commit failed tests in one use case (by a sample application), and just fixed the above **None** case so requires more testing.

Thx! 😊
