### ISSUE TITLE
Updates: Refactoring and bug fixes

### ISSUE THREAD

**Issue by paulushub** [dotnetprojects/SVGImage#73]
@jogibear9988 I have made a number of changes to the codes. The changes are available in my fork below;

[Refactoring and bug fixes](https://github.com/dotnetprojects/SVGImage/commit/8c2104d62a754b23b0271ab996bdbaa7cba27090) 

- Removed the Design project
- Removed the VS2017 project files
- Removed .NETCore 3.0
- Removed DotnetProjects namespaces, simplified the namespaces
- Removed the Attribute class, since it is the same as StyleItem class
- Added DocFX projects for building documentations
- Updates to the Nuget package: included Xml-docs, readme etc.
- Fixed null exception in the ViewBoxToSizeNoStretch support when using Drawing sources.

**NOTE**: The changes will results in breakings changes in the API, as
* I have removed the DotnetProjects namespaces (for simplicity and documentation),
* Made the utility classes internal. and
* Eliminated most of the nested classes for simplicity.

**But** there is no breaking change in binary output, and any current project using only the controls will work as usual.

You can check the changes, if you like them, I will add support for .NET6/7 and create a PR.

The output of the document is shown below (others can contribute to improve it):
**NOTE:** You preview the current documentation  [deployed here](https://paulushub.github.io/SVGImage/index.html) with GitHub action.

![image](https://github.com/dotnetprojects/SVGImage/assets/809351/03d222c0-84ae-405c-81cb-3bfa497d764b)

**Comment by jogibear9988** [comment]
like it !

**Comment by jogibear9988** [comment]
I think, with the Design Project, you could select a File for the Source Property (it showed a File Selector). If it worked...
Don't know if it did....
Are Design Assemblies still a thing with netcore WPF?
But for me it's okay to remove

**Comment by jogibear9988** [comment]
You should increase the Major version, at it is a breaking change, cause if someone used the namspace import in xaml instead of the uri, it will break. Also if someone used the contrl in c# code, as the namespaces changed.

**Comment by paulushub** [comment]
Thanks for the response. 
On the version update, I have never used the **appveyor.yml** CD/CI build.
The version there is `version: 4.1.{build}`, that in the `DotNetProjects.SVGImage.cproj` is `3.0.0.0`.

What do you suggest? Will it work if I set that in project file to `5.0.0.0` and in the appveyor.yml to 
something like `version: 5.0.{build}`?

**Comment by paulushub** [comment]
The license contains: 
Copyright (c) 2014 PropertyTools contributors

Do you want any change? At least the year could change.

**Comment by jogibear9988** [comment]
> Thanks for the response. On the version update, I have never used the **appveyor.yml** CD/CI build. The version there is `version: 4.1.{build}`, that in the `DotNetProjects.SVGImage.cproj` is `3.0.0.0`.
> 
> What do you suggest? Will it work if I set that in project file to `5.0.0.0` and in the appveyor.yml to something like `version: 5.0.{build}`?

think so

**Comment by jogibear9988** [comment]
> The license contains: Copyright (c) 2014 PropertyTools contributors
> 
> Do you want any change? At least the year could change.

maybe name PropertyTools and dotnetprojects and change year

**Comment by paulushub** [comment]
OK! If I understand it, then

Copyright (c) 2023 PropertyTools and DotNetProjects  contributors

or 
Copyright (c) 2020-2023 PropertyTools and DotNetProjects  contributors

**Comment by paulushub** [comment]
On **appveyor.yml**: The configuration is **Debug**, I do not understand why but changed it to **Release**, hope it is OK with you.
![image](https://github.com/dotnetprojects/SVGImage/assets/809351/8f8deba5-94dd-47d6-bee3-ac0568f9d78c)
