### ISSUE TITLE
Default permission with FileSource

### ISSUE THREAD

**Issue by sderrico** [dotnetprojects/SVGImage#8]
Hello jogibear9988,

Is it possible to specify the read file access when opening a file stream? By default, I suspect it opening the file in ReadWrite causing an exception when the application is located inside of program files.

From SVGImage/SVGImage/SVG/**SVGImage**.cs at line 63

Replacing

`((SVGImage)d).SetImage(new FileStream(e.NewValue.ToString(), FileMode.Open));`

To

`((SVGImage)d).SetImage(new FileStream(e.NewValue.ToString(), FileMode.Open, FileAccess.Read));`

Thank you!
Sebastien

**Comment by jogibear9988** [comment]
will do
