### ISSUE TITLE
[BUG]6.svg display failed in example

### ISSUE THREAD

**Issue by guojiancong** [dotnetprojects/SVGImage#89]
**Describe the bug**
6.svg display failed in example

**To Reproduce**
1. Start example
2. See error

**Expected behavior**
![2](https://github.com/dotnetprojects/SVGImage/assets/1125823/af9f94c8-8591-45aa-a3b5-c9f16a8650d9)

**Screenshots**
![1](https://github.com/dotnetprojects/SVGImage/assets/1125823/4c28b317-11e6-4505-a02f-74d32cb0df0f)

**Additional context**

**Comment by paulushub** [comment]
@guojiancong Nice catch - thanks. 
I have simply assumed that was the expected result since it was the case when I started contributing.
