### ISSUE TITLE
Visibility bug starting from version 2.0.20

### ISSUE THREAD

**Issue by raffaeler** [dotnetprojects/SVGImage#9]
Hello, I tried to use 2.0.20 and 2.0.21 (nuget versions) in an application that overlaps several drawings inside an ItemsControl.
The app works well until (including) 2.0.16 but after this release, the drawings are not visible anymore.
Using the diagnostics tool in Visual Studio I can see the visibility of the SVGImage control is set to Visible, anyway there is nothing on screen.
As soon as I rollback the nuget package to 2.0.16, everything works again.

P.S. it would be useful if you could label the source code in GitHub with the version published on NuGet.

Thanks for your help.

**Comment by jogibear9988** [comment]
maybe its cause of https://github.com/dotnetprojects/SVGImage/commit/9eef421a19301d114247145c4939de92ab8eb5fd

**Comment by jogibear9988** [comment]
I'm wrong think https://github.com/dotnetprojects/SVGImage/commit/9eef421a19301d114247145c4939de92ab8eb5fd is already included in 16
Nee a sample to reproduce the issue.

**Comment by jogibear9988** [comment]
@raffaeler do you have more info?

**Comment by raffaeler** [comment]
@jogibear9988 Sorry but I am busy at work. I will try to create a repro. Basically if you create an ItemControl loading the maps in binding, you should see the problem.
I use the ItemsControl because I need to overlapy multiple layers.

**Comment by jogibear9988** [comment]
@raffaeler any progress with the repro?

**Comment by raffaeler** [comment]
Hi @jogibear9988 
I finally found the time to create the repro:
[WpfSvgOvarlap.zip](https://github.com/dotnetprojects/SVGImage/files/2707442/WpfSvgOvarlap.zip)

Some notes:
- It now references version 2.0.29 and the demo does not show anything
- If you downgrade the library to version 2.0.16 it works (it shows few basic colored shapes overlapped
- There is some useless code in the demo. I had to reparse the svgs to grab the coordinates of each object so that I can highlight, and center the object in the window. I currently left some (not all) of this code in the demo to obtain a working demo as fast as I can. You can just ignore those parts (SvgMap, SvgPath, SvgPathParser, etc.).
- I also removed the dependency on my own MVVM framework but I had to bind the demo to the viewmodels otherwise the timings of the binding would probably affect the results.
- It is fundamental to bind the layers to see the failure. If you overlap just putting multiple fixed shapes on the screen it won't show the problem.

If you have other questions, please let me know.

**Comment by jogibear9988** [comment]
fixed

**Comment by raffaeler** [comment]
Thank you!

**Comment by jogibear9988** [comment]
In your image 2.svg you also used colors like "rbg(...)" which were not supported yet. I fixed this also.

**Comment by raffaeler** [comment]
Great. I took the sample images randomly from some free image website, but good to know :)
