### ISSUE TITLE
[BUG] NullReferenceException when placing an SVGImage inside a DataGridCheckboxColumn

### ISSUE THREAD

**Issue by lukas-kirschner** [dotnetprojects/SVGImage#94]
**Describe the bug**
When I place an SVGImage inside a DataGridCheckboxColumn and change the DataContext, my program crashes with a `System.NullReferenceException` inside the `OnSourceChanged` method of the SVGImage.

**To Reproduce**
1. Create a User Control X with a Datagrid and a DataGridCheckboxColumn, place an SVGImage inside the DataGridCheckboxColumn and set its URI to a relative path that points to an existing SVG resource
2. Create a ContentPresenter inside a different UserControl
3. Programmatically change the Content of the ContentControl to different instances of the UserControl X

**Expected behavior**
The SVGImage is displayed correctly with its Source set to some existing URI, and invisible with the source set to Null or DependencyProperty.UnsetValue.

**Additional context**
The problem occurred with SVGImage 5.1.1 and .NET8

**Comment by jogibear9988** [comment]
thx

**Comment by larshjohannesson** [comment]
We have this issue also. Is there any release pending to Nuget including this fix?

**Comment by jogibear9988** [comment]
released atm. will take a few minutes on nuget

**Comment by larshjohannesson** [comment]
> released atm. will take a few minutes on nuget
We have updated to 5.2.0 from Nuget but still seeing the issue. From what I can see on Github release 5.20 is still based on source from Dec 2023?
![image](https://github.com/dotnetprojects/SVGImage/assets/1419698/2ae2f3d0-ad7a-4d5e-9051-ebd8d9e559a4)

**Comment by jogibear9988** [comment]
Now?

**Comment by larshjohannesson** [comment]
> Now?

Yes, thank you!
